name: "Deploy portal"

on:
  workflow_call:
    inputs:
      portal-name:
        required: true
        type: string

jobs:
  build-and-deploy:
    name: build-and-deploy
    # limit to this repository
    runs-on: ubuntu-latest
    # Allow OIDC Integration (so we can assume the AWS role to deploy)
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: setup
        uses: ./.github/actions/pnpm-setup-action
      - name: build
        run: |
          cd apps/portals
          chmod +x ./build.sh
          ./build.sh ${{ inputs.portal-name }}
      - name: setup-outputbucket-staging
        if: github.ref == 'refs/heads/releases/portals/staging'
        run: |
          ls -l
          echo chmod +x ./deploy.sh
          echo bash -c ./deploy.sh push-staging ${{ inputs.portal-name }}
      - name: setup-outputbucket-prod
        if: github.ref == 'refs/heads/releases/portals/production'
        run: |
          ls -l
          echo chmod +x ./deploy.sh
          echo bash -c ./deploy.sh WARNING-push-production ${{ inputs.portal-name }}