name: "Deploy AD Knowledge Portal"

on:
  push:
    branches:
      - releases/portals/staging
      - main
    paths:
      - "apps/portals/**"
      - "!apps/portals/src/configurations/**"
      - "apps/portals/src/configurations/adknowledgeportal/**"
      - "packages/synapse-react-client/**"

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      portal-name: adknowledgeportal
