name: Deploy production portal

on:
  workflow_dispatch:
    inputs:
      portal-name:
        type: choice
        description: Portal to deploy
        options: 
        - adknowledgportal
        - challengeportal

jobs:
  build-and-deploy:
    name: build-and-deploy
    # limit to this repository
    runs-on: ubuntu-latest
    # Allow OIDC Integration (so we can assume the AWS role to deploy)
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
        with:
          ref: releases/portals/production
      - uses: ./.github/actions/pnpm-setup-action
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::797640923903:role/sagebase-github-oidc-sage-bionetworks-web-monorepo-infra
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200
      - name: setup-outputbucket-prod
        run: |
          cd apps/portals
          echo chmod +x ./deploy.sh
          echo ./deploy.sh WARNING-push-production ${{ inputs.portal-name }}